services:

  redis:
    image: redis:7.2.3-alpine

  db:
    image: postgres:12.17-alpine3.19
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    depends_on:
      - redis
  
  django:
    image: .
    command: >
            bash -c " python3 manage.py createsuperuser --noinput &&
            python3 manage.py runscript populate_puzzles &&
            python3 manage.py collectstatic --no-input --clear &&
            daphne -b 0.0.0.0 -p 8000 app.asgi:application"
    # command: >
    #         bash -c "python3 manage.py createsuperuser --noinput &&
    #         python3 manage.py runscript populate_puzzles &&
    #         daphne -b 0.0.0.0 -p 8000 app.asgi:application"
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  celery:
    buıld: .
    entrypoint: bash -c "./wait_for_migrations.sh && celery -A app worker -l info"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - django
  
  celery-beat:
    buıld: .
    entrypoint: bash -c "./wait_for_migrations.sh && celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - django
    environment:
      - POSTGRES_USER=postgres_user_test
      - POSTGRES_PASSWORD=postgres_password_test
      - POSTGRES_DB=postgres_db_test

  nginx:
    restart: always
    buıld: .
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - django


volumes:
  postgres_data:
  static_volume:
