# Generated by Django 4.2.7 on 2023-11-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='initial_board',
            field=models.CharField(default='', max_length=81),
        ),
        migrations.AddField(
            model_name='room',
            name='solved_board',
            field=models.CharField(default='', max_length=81),
        ),
    ]
