# Generated by Django 4.2.7 on 2023-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_room_initial_board_room_solved_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='eligible_points',
            field=models.CharField(default='', max_length=81),
        ),
        migrations.AlterField(
            model_name='board',
            name='current_board',
            field=models.CharField(default='', max_length=81),
        ),
        migrations.AlterField(
            model_name='board',
            name='initial_board',
            field=models.CharField(default='', max_length=81),
        ),
        migrations.AlterField(
            model_name='board',
            name='solved_board',
            field=models.CharField(default='', max_length=81),
        ),
    ]
