# Generated by Django 4.2.7 on 2023-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_room_eligible_points_alter_board_current_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='solved_board',
        ),
        migrations.AddField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
