# Generated by Django 4.2.7 on 2023-12-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0007_remove_room_initial_board_remove_room_solved_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='puzzle',
        ),
        migrations.AddField(
            model_name='room',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sudoku.puzzle'),
        ),
    ]
