# Generated by Django 4.2.7 on 2023-12-04 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sudoku', '0009_board_tiles_left_room_status_room_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
